### ISSUE TITLE
火钳刘明 

### ISSUE THREAD

**Issue by onesez** [Vittfarne/ASSL#1]
火钳刘明 火钳刘明 火钳刘明

**Comment by forkgood** [comment]
watch it 火钳刘明

**Comment by onesez** [comment]
which country are you from?

**Comment by forkgood** [comment]
@onesez I am from the HOSTLOC empire.

**Comment by onesez** [comment]
你是中国人吧，我的哥

**Comment by forkgood** [comment]
@onesez Let't talk in English, and you are word G ！:D:D:D:D

**Comment by onesez** [comment]
小逼，跟我一起说中文行不行！

**Comment by forkgood** [comment]
@onesez 好之者，曰中文 💃 💃 💃 💃

**Comment by onesez** [comment]
你的标点符号暴露了你

**Comment by onesez** [comment]
有么有LOC宴请码，我的账号被疯了

**Comment by forkgood** [comment]
What's your QQ  number,my nickname is 魅影

**Comment by onesez** [comment]
对，你很聪明，

**Comment by forkgood** [comment]
Welcome to the QQ Group: 161921952

**Comment by neoFelhz** [comment]
Hey you two guys,Issue shouldn't be used in this way...

**Comment by onesez** [comment]
你英语都不会，
嘿你两个家伙，问题shoulidn't这样使用...
Hēi nǐ liǎng gè jiāhuo, wèntí shoulidn't zhèyàng shǐyòng...

**Comment by neoFelhz** [comment]
@onesez  I surely consider that you are using translation website or application.I had use it to communicate with Chinese before.

**Comment by forkgood** [comment]
@neoFelhz have any updates to your code, I'll watch it.

**Comment by neoFelhz** [comment]
In fact I'm using Coding.io now,for it provides free private repository.

**Comment by Vittfarne** [comment]
Issues is not a chat, please get in contact by other means :)
Time to close this! :)
