### ISSUE TITLE
I met some problems on the PHP set!

### ISSUE THREAD

**Issue by Jinooh** [Vittfarne/ASSL#10]
> Notice: Undefined variable: argc in /www/wwwroot/assl.impoi.com/index.php on line 33
Notice: Undefined index: id in /www/wwwroot/assl.impoi.com/index.php on line 34
Notice: Undefined index: _ in /www/wwwroot/assl.impoi.com/index.php on line 35

How do these problems need to be solved?
I'm using the BT panel
If you are convenient to test, I will provide an installation link for the BT panel. : )
URL：http://www.bt.cn/
This is a WEB panel in China
I hope to solve the above problems! Thank you very much here!

**Comment by Vittfarne** [comment]
You could set error_reporting to 0 on line 29 (https://github.com/Vittfarne/ASSL/blob/master/web/html/index.php#L29) to most likely get rid of the warnings.

`error_reporting(0);`
