### ISSUE TITLE
Does not work assl.loovit.net 

### ISSUE THREAD

**Issue by o7er1ord** [Vittfarne/ASSL#3]
assl.loovit.net
Does not work

And what to do if you accidentally deleted emails?
My mail 0verl0rd@protonmail.ком my domains 0x00.pro over-lord.pro moon-house.pro over-lord.info.  
You can send an emails again or send the certificates?

**Comment by o7er1ord** [comment]
Strange (.. working.... But in the letter mail does not come (

**Comment by o7er1ord** [comment]
Help me!

**Comment by Vittfarne** [comment]
I see multiple certs issued for some of the domains, have you still not received the certificates?
