### ISSUE TITLE
Certificate issuing procedure failure

### ISSUE THREAD

**Issue by forkgood** [Vittfarne/ASSL#4]
I use the demo site(assl.loovit.net)certificate issuing procedures, but there can not be issued, I would like to ask the program encountered any difficulties.

Thanks.

**Comment by Vittfarne** [comment]
Currently there is an issue with the SH website and it's not possible to issue certs. Hopefully SH will have a fix for this shortly. It seems to have stopped working on the 5th as that's when the last cert was issued.

**Comment by forkgood** [comment]
I see, thank you for your answer, I think it should be singlehop made restrictions, looking forward to the resumption of singlehop issued as soon as possible. 
Have a nice day.
