### ISSUE TITLE
assl have error on current implementation

### ISSUE THREAD

**Issue by msva** [Vittfarne/ASSL#6]
Hi there!
I just tried to "order" certificate, and found that "last name field" does not work (the surname in end certificate is "Doe" anyway)

**Comment by Vittfarne** [comment]
Just tried and it works as it should.

**Comment by msva** [comment]
And I have tried just yesterday and still got certificates with "Doe" as last name.

Can you try with double-worded surname (you can take mine for test, or take any other)?

Can't it be a bug of parsing hyphen ("-") in the last name string?

**Comment by ArjonBu** [comment]
@msva can you please tell me how did you make this script work? I have entered my username and password on the index.php file but it returns "CSR invalid".
