### ISSUE TITLE
Setup failed (Somehow)

### ISSUE THREAD

**Issue by szhu25** [Vittfarne/ASSL#9]
Hi,

I just tried to set this up, and after successfully setup (as i think).  Pasting CSR into just didn't work.

Error Message:
Oops... SSL issue is already under process for this CSR. Please wait few minutes before trying again.

**Comment by szhu25** [comment]
I tried someone's site on LET, assl.space.
That is working, (somehow i don't receive the email though)

AT least it's better than mine.

**Comment by szhu25** [comment]
The small point which is making things worse is, i never successfully issued a cert since i created the account (signed up for SH service). What the rep told me is "There is software limitations". Is it possible that SH limited SSL issuance?

**Comment by Vittfarne** [comment]
Still having issues?

If you are, try clearing the data folder and try again.
